# for updates and superuser setup, please use:
 # docker-compose run python migrate
# docker-compose run

version: "3.4"
services:

  db:
    ports:
      - "127.0.0.1:5432:5432"

  python:
    ports: [ ]
    # - "127.0.0.1:8000:8000"
    environment:
      ACTIVATE_DEBUG_MODE:

  opa:
    ports:
      - "127.0.0.1:8181:8181"
    environment:
      OPA_DEBUG_MODE: 'unauthenticated'
      OPA_BUNDLE_SERVER_URL: "http://host.docker.internal:8000/opa-bundles/"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    ports:
      - "127.0.0.1:8080:80"

volumes:
  opa-client-prototype-persistence:
  ldap-data:
  ldap-config: