# for updates and superuser setup, please use:
# docker-compose run python migrate
# docker-compose run

version: "3.4"

networks:
  web: # nginx <--> django
    external:
      name: nginx_door_commander_external
  inventory_management:
    external:
      name: nginx_inventory_management_external

