# Generated by Django 5.2.5 on 2025-08-13 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('some_second_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('display_name', models.TextField()),
                ('order', models.IntegerField(default=42, help_text='Order of appearance for door buttons. Lower is higher up.')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
